import logging

LOGGING_LEVEL = logging.NOTSET

SERVER_ADDR = ("localhost", 14867)
SERVER_TIMEOUT = 2
SERVER_WAIT_MSG_TIMEOUT = 0.1
SERVER_LOGGING_LEVEL = logging.DEBUG

EVENTBUS_LOGGING_LEVEL = logging.DEBUG
THREADS_GC_TIMEOUT = 2
