import logging

LOGGING_LEVEL = logging.DEBUG

SERVER_ADDR = ("localhost", 14867)
SERVER_TIMEOUT = 2
SERVER_WAIT_MSG_TIMEOUT = 0.1
SERVER_LOGGING_LEVEL = logging.DEBUG

EVENTBUS_LOGGING_LEVEL = logging.DEBUG
THREADS_GC_TIMEOUT = 2

GUI_TITLE_NAME = "HEYE Overlay"
GUI_TOGGLE_HOTKEY = "right shift"

NOTIFY_LOGGING_LEVEL = logging.ERROR

VEYON_DETECTOR_LOGGING_LEVEL = logging.INFO
VEYON_DETECTOR_SCAN_DELAY = 1.5
